# Generated by Django 5.2.3 on 2025-06-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="author",
            field=models.CharField(max_length=50),
        ),
    ]
