# Generated by Django 5.2.3 on 2025-06-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "quotes_app",
            "0003_author_tag_remove_quote_updated_at_alter_quote_quote_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
